apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: {{ include "svt-go.fullname" . }}
  labels:
    app: {{ include "svt-go.name" . }}
    chart: {{ include "svt-go.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.selector.name }}
  selector:
    app: {{ include "svt-go.name" . }}
    release: {{ .Release.Name }}