apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ include "svt-go.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    app: {{ include "svt-go.name" . }}
    release: {{ .Release.Name }}
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: {{ include "svt-go.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
  triggers:
  - type: ConfigChange
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}